// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package structs

import (
	"time"
)

const TableNameTakeOverHistoryNew = "takeover_history_new"

// TakeOverHistoryNew mapped from table <takeover_history_new>
type TakeOverHistoryNew struct {
	ID             string     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RequestUserID  int32      `gorm:"column:request_user_id" json:"request_user_id"`
	UserID         int32      `gorm:"column:user_id" json:"user_id"`
	Datetime       string  	  `gorm:"column:datetime" json:"datetime"`
	DatetimeEnd    string 	  `gorm:"column:datetime_end;default:null" json:"datetime_end"`
	CreatedAt      time.Time  `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt      time.Time  `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName TakeOverHistoryNew's table name
func (*TakeOverHistoryNew) TableName() string {
	return TableNameTakeOverHistoryNew
}
